spring:
  main:
    banner-mode: "off"
  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

secret:
  jwt: "jwt-secret-et-webiste-test-jwt-secret-et-webiste-test"