app:
  file-properties:
    upload-path: "/home/elmirtaghisoy/ETProjects/uploads"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/etwebsite
    username: user_et
    password: user_et

  jpa:
    show-sql: false
    hibernate:
      format_sql: false
      ddl-auto: update

  redis:
    client-name: JEDIS
    host: redis
    port: 6379
    timeout: 3000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "538981183295-d6g8ir58b4b0tqedouikd2lb726pmbd7.apps.googleusercontent.com"
            client-secret: "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"
            scope:
              - email
              - profile

  kafka:
    consumer:
      bootstrap-servers: kafka:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081
