spring:
  datasource:
    url: jdbc:mysql://localhost:3306/etwebsite
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
  redis:
    client-name: JEDIS
    host: localhost
    port: 6379
    timeout: 3000

server:
  port: 8081
