spring:
  datasource:
    url: jdbc:mysql://localhost:3306/etwebsite
    username: user_et
    password: user_et
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080
