spring:
  datasource:
    url: jdbc:mysql://localhost:3306/etwebsite
    username: user_et
    password: user_et
  jpa:
    hibernate:
      ddl-auto: create
  redis:
    client-name: JEDIS
    host: redis
    port: 6379
    timeout: 3000
server:
  port: 8081
